repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        exclude: ^src/blib2to3/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks # Some out-of-the-box hooks for pre-commit
    rev: "v4.3.0"
    hooks:
      - id: check-yaml # This hook checks yaml files for parseable syntax
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline
        exclude: requirements*.txt
      - id: trailing-whitespace # This hook trims trailing whitespace
        exclude: requirements*.txt
