[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
)/
'''

[tool.isort]
py_version = 311
profile = 'black'


[tool.mypy]
follow_imports = 'skip'
ignore_missing_imports = 'True'
pretty = 'True'
show_error_codes = 'True'
show_error_context = 'True'
warn_redundant_casts = 'True'
exclude = ['.venv/*']
